# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./.env.docker:/app/.env
      - ppiwd_dataset:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  ppiwd_dataset:
